### ISSUE TITLE
Unlist the AutoFixture.NUnit3.AutoDataConnector package on NuGet

### ISSUE THREAD

**Issue by zvirja** [hackle/AutoFixture.NUnit3.AutoDataConnector#1]
Hi @hackle,

I've found that his repository belongs to the [AutoFixture.NUnit3.AutoDataConnector](https://www.nuget.org/packages/AutoFixture.NUnit3.AutoDataConnector/) NuGet package.

The package name you used is a bit confusing as it might look like this package is a part of the AutoFixture packages family. Recently we have reserved the `AutoFixture.*` package ID prefix so only AutoFixture could publish packages with such name in future, however old packages left untouched. Therefore I'm here to discuss that 😃

Would you be fine to unlist the package on NuGet, so it's no longer visible in the search? That would cause less confusion to our new clients.  Also I've found that this package provides feature that is a part of the AutoFixture now, so it's no longer required.

If you would like to contribute extensions to the AutoFixture in future, please use the `AutoFixture.Community` package prefix - the ownership will be much clear. We are going to make this package prefix available to everybody.

Thanks a lot for your time and let me know if you have any concerns! Also let me know if I'm missing something.

**Comment by hackle** [comment]
hey thanks for the message I should have done this right after the official package was published. Have unlisted this package. Let me know if it's ok now?

**Comment by zvirja** [comment]
@hackle Thanks a lot for that. Yep, it's fine now 😉🎉

Hope, one day we'll have a lot of  `AutoFixture.Community.*` extending AutoFixture, so feel free to create packages there if you have any valuable addition which couldn't be a part of the core 😉
